# Data Transformation
------

Transform the data into a format so that we can insert it into the time series transformer<br>

Model input dimensions:<br>
Axis 0 (nested): ID, sample<br>
Axis 1 : Variable
<br>

Goal of the transformation: <br>
Axis 0: Participant ID, time point<br>
Axis 1: Channel

In [1]:
import cedalion
import cedalion.nirs
import cedalion.xrutils as xrutils
from cedalion.datasets import get_multisubject_fingertapping_snirf_paths
import numpy as np
import xarray as xr
import pint
import matplotlib.pyplot as p
import scipy.signal
import os.path

import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.metrics import accuracy_score

xr.set_options(display_max_rows=3, display_values_threshold=50)
np.set_printoptions(precision=4)
try:
    cedalion.units.define('@alias meter = o')
except:
    pass

In [2]:
fnames = get_multisubject_fingertapping_snirf_paths()
subjects  = [f"sub-{i:02d}" for i in [1,2,3,4,5]]

# store data of different subjects in a dictionary
data = {} 
for subject,fname in zip(subjects, fnames):
    print(fname)
    elements = cedalion.io.read_snirf(fname)

    amp = elements[0].data[0]
    stim = elements[0].stim # pandas Dataframe
    geo3d = elements[0].geo3d
    
    # cedalion registers an accessor (attribute .cd ) on pandas DataFrames
    stim.cd.rename_events( {
        "1.0" : "control",
        "2.0" : "Tapping/Left",
        "3.0" : "Tapping/Right"
    })
    
    dpf = xr.DataArray([6, 6], dims="wavelength", coords={"wavelength" : amp.wavelength})
    
    data[subject] = xr.Dataset(
        data_vars = {
            "amp" : amp,
            "od"  : - np.log( amp / amp.mean("time") ),
            "geo" : geo3d,
            "conc": cedalion.nirs.beer_lambert(amp, geo3d, dpf)
        },
        attrs={"stim" : stim}, # store stimulus data in attrs
        coords={"subject" : subject} # add the subject label as a coordinate
    )

/Users/idalabbackup/Library/Caches/cedalion/multisubject-fingertapping.zip.unzip/BIDS-NIRS-Tapping/sub-01/nirs/sub-01_task-tapping_nirs.snirf
/Users/idalabbackup/Library/Caches/cedalion/multisubject-fingertapping.zip.unzip/BIDS-NIRS-Tapping/sub-02/nirs/sub-02_task-tapping_nirs.snirf
/Users/idalabbackup/Library/Caches/cedalion/multisubject-fingertapping.zip.unzip/BIDS-NIRS-Tapping/sub-03/nirs/sub-03_task-tapping_nirs.snirf
/Users/idalabbackup/Library/Caches/cedalion/multisubject-fingertapping.zip.unzip/BIDS-NIRS-Tapping/sub-04/nirs/sub-04_task-tapping_nirs.snirf
/Users/idalabbackup/Library/Caches/cedalion/multisubject-fingertapping.zip.unzip/BIDS-NIRS-Tapping/sub-05/nirs/sub-05_task-tapping_nirs.snirf


In [3]:
display(data["sub-01"])

<xarray.Dataset> Size: 32MB
Dimensions:     (time: 23239, channel: 28, wavelength: 2, label: 55, pos: 3,
                 chromo: 2)
Coordinates: (3/10)
  * time        (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples     (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
    ...          ...
    subject     <U6 24B 'sub-01'
Dimensions without coordinates: pos
Data variables: (3/4)
    amp         (channel, wavelength, time) float64 10MB [] 0.09137 ... 1.276
    od          (channel, wavelength, time) float64 10MB [] 0.04042 ... -0.01317
    ...          ...
    conc        (chromo, channel, time) float64 10MB [µM] 0.1336 ... -1.076
Attributes:
    stim:            onset  duration  value     trial_type\n0     61.824     ...

In [4]:
data["sub-01"].time.samples[-1] / data["sub-01"].time.time[-1]

<xarray.DataArray ()> Size: 8B
array(7.8125)
Coordinates:
    time     float64 8B 2.974e+03
    samples  int64 8B 23238
    subject  <U6 24B 'sub-01'

In [5]:
con = data["sub-01"].conc
con

<xarray.DataArray 'conc' (chromo: 2, channel: 28, time: 23239)> Size: 10MB
<Quantity([[[ 0.1336  0.0038  0.3486 ...  0.4427  0.5027  0.6633]
  [-0.7839 -0.764  -0.6372 ...  0.2308  0.2051  0.1698]
  [ 0.1121  0.0731  0.2339 ...  0.1596  0.1966  0.1289]
  ...
  [-0.09    0.2976  0.3035 ...  0.571   0.5274  0.3771]
  [ 0.9042  1.3401  1.3813 ... -0.272  -0.2675 -0.4013]
  [-0.1858  0.4272  0.6069 ... -0.3056 -0.2959 -0.4928]]

 [[ 0.4303  0.5291  0.3941 ... -0.0381 -0.0488 -0.1695]
  [ 0.1972  0.0748  0.2147 ... -0.1305 -0.1586 -0.1213]
  [ 1.107   1.1056  1.1824 ... -0.384  -0.3401 -0.3184]
  ...
  [ 1.131   1.1631  1.1133 ... -0.6598 -0.6095 -0.6461]
  [ 1.8251  1.8989  1.8366 ... -0.8552 -0.8545 -0.8731]
  [ 3.6719  3.6383  3.5445 ... -1.0729 -1.067  -1.0756]]], 'micromolar')>
Coordinates: (3/7)
  * time      (time) float64 186kB 0.0 0.128 0.256 ... 2.974e+03 2.974e+03
    samples   (time) int64 186kB 0 1 2 3 4 5 ... 23234 23235 23236 23237 23238
    ...        ...
    subject   <U6 24B 'sub-01'

In [6]:
def pad_along_axis(array: np.ndarray, target_length: int, axis: int = 0) -> np.ndarray:

    pad_size = target_length - array.shape[axis]

    if pad_size <= 0:
        return array

    npad = [(0, 0)] * array.ndim
    npad[axis] = (0, pad_size)

    return np.pad(array, pad_width=npad, mode='constant', constant_values=0)

In [7]:
from typing import Dict

def into_dataframe(subject_array:Dict[str, xr.DataArray]) -> pd.DataFrame:
    """Turns a dictionary with subject data in xarray form into a TST compatible dataframe.
     
     WARNING: Currently, channels are simply concatenated.
        This means that the channel sorting depends on the ordering of channels within the data.
        Therefore it is prespecified by the data that is read.
    """
    
    # Find out longest sample length
    longest_ts = 0
    for sub, d in subject_array.items():
        if d.conc.shape[-1] > longest_ts:
            longest_ts = d.conc.shape[-1]
    print(f"Padding data to longest sequence with length: {longest_ts}")

    # Transform matrix into TST shape
    all_subs = []
    for sub in subject_array.values():
        b = pad_along_axis(np.array(sub.conc), longest_ts, axis=-1)
        c = np.concatenate(b, axis=0)
        all_subs.append(c)

    padded = np.stack(all_subs, 0)
    padded_2d = np.concatenate(padded, -1).T

    # create index
    n_subjects = np.arange(padded.shape[0])
    n_samples = longest_ts

    # Creates an index for each subject
    index = np.repeat(n_subjects, n_samples)

    df = pd.DataFrame(data=padded_2d, index=index)

    return df

test = into_dataframe(data)
test.head()

Padding data to longest sequence with length: 23239


/usr/local/Caskroom/miniconda/base/envs/cedalion/lib/python3.10/site-packages/xarray/core/variable.py:306: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


0         1         2         3         4         5         6    
0  0.133582 -0.783922  0.112124 -6.605575  0.072065  0.157804 -0.165179  \
0  0.003830 -0.764006  0.073132 -6.785065  0.105426  0.146239 -0.140950   
0  0.348566 -0.637232  0.233887 -6.464715  0.297150  0.405250  0.073547   
0  0.191469 -0.696672  0.328634 -6.319006  0.257867  0.375040  0.020626   
0  0.415568 -0.553111  0.426234 -6.267730  0.263309  0.466229  0.016447   

         7         8         9   ...        46        47        48        49   
0 -2.991802 -0.662061 -0.650387  ...  1.657113  1.165608  1.689860  1.595643  \
0 -2.917413 -0.457271 -0.544232  ...  1.710501  1.213622  1.719345  1.582520   
0 -2.674065 -0.352645 -0.511028  ...  1.707331  1.272164  1.695244  1.649482   
0 -2.615859 -0.316476 -0.322001  ...  1.758502  1.176429  1.697077  1.736220   
0 -2.560593 -0.215540 -0.329690  ...  1.679600  1.200704  1.705122  1.539560   

         50        51        52        53        54        55  
0  0.979688  1.081886 -1.353489  1.131007  1.825085  3.671882  
0  0.993582  1.190909 -1.235771  1.163109  1.898854  3.638324  
0  0.950616  1.073023 -1.287167  1.113292  1.836601  3.544473  
0  1.089578  1.207084 -1.291210  1.138696  1.885575  3.566036  
0  1.074913  1.232196 -1.363738  1.045494  1.869924  3.492447  

[5 rows x 56 columns]

# READ IN CUSTOM STUDY DATA
-------
Given any generic directory, find all snirf files and combine them based on subject

In [8]:
import pathlib

vfc = pathlib.Path('../fnirs_data/vfc_high_density/')
fnames = sorted(list(vfc.rglob("*.snirf")))
subjects  = [f"sub-{i:02d}" for i in range(1, len(fnames)+1)]
# store data of different subjects in a dictionary
data = {} 
for subject,fname in zip(subjects, fnames):
    print(fname)
    elements = cedalion.io.read_snirf(fname)

    amp = elements[0].data[0]
    stim = elements[0].stim # pandas Dataframe
    geo3d = elements[0].geo3d
    # cedalion registers an accessor (attribute .cd ) on pandas DataFrames
    # stim.cd.rename_events( {
    #     "1.0" : "control",
    #     "2.0" : "Tapping/Left",
    #     "3.0" : "Tapping/Right"
    # })
    # TODO: Talk to Eike whether this is needed
    
    dpf = xr.DataArray([6, 6], dims="wavelength", coords={"wavelength" : amp.wavelength})
    
    data[subject] = xr.Dataset(
        data_vars = {
            "amp" : amp,
            "od"  : - np.log( amp / amp.mean("time") ),
            "geo" : geo3d,
            "conc": cedalion.nirs.beer_lambert(amp, geo3d, dpf)
        },
        attrs={"stim" : stim}, # store stimulus data in attrs
        coords={"subject" : subject} # add the subject label as a coordinate
    )


../fnirs_data/vfc_high_density/sub-01/ses-02/nirs/nirs.snirf
../fnirs_data/vfc_high_density/sub-06/ses-01/nirs/sub-06_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-08/ses-01/nirs/sub-08_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-09/ses-01/nirs/sub-09_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-11/ses-01/nirs/sub-11_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-12/ses-01/nirs/sub-12_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-13/ses-01/nirs/sub-13_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-14/ses-01/nirs/sub-14_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-15/ses-01/nirs/sub-15_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-17/ses-01/nirs/sub-17_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-20/ses-01/nirs/sub-20_

/usr/local/Caskroom/miniconda/base/envs/cedalion/lib/python3.10/site-packages/pint/facets/numpy/numpy_func.py:307: RuntimeWarning: divide by zero encountered in log
  result_magnitude = func(*stripped_args, **stripped_kwargs)
/usr/local/Caskroom/miniconda/base/envs/cedalion/lib/python3.10/site-packages/pint/facets/numpy/numpy_func.py:307: RuntimeWarning: divide by zero encountered in log
  result_magnitude = func(*stripped_args, **stripped_kwargs)


../fnirs_data/vfc_high_density/sub-24/ses-01/nirs/sub-24_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-25/ses-01/nirs/sub-25_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-26/ses-01/nirs/sub-26_ses-01_task-WordStroop_run-01_nirs.snirf
../fnirs_data/vfc_high_density/sub-27/ses-01/nirs/sub-27_ses-01_task-WordStroop_run-01_nirs.snirf


/usr/local/Caskroom/miniconda/base/envs/cedalion/lib/python3.10/site-packages/pint/facets/numpy/numpy_func.py:307: RuntimeWarning: divide by zero encountered in log
  result_magnitude = func(*stripped_args, **stripped_kwargs)
/usr/local/Caskroom/miniconda/base/envs/cedalion/lib/python3.10/site-packages/pint/facets/numpy/numpy_func.py:307: RuntimeWarning: divide by zero encountered in log
  result_magnitude = func(*stripped_args, **stripped_kwargs)


In [9]:
len(data.keys())

17

In [10]:
test = into_dataframe(data)
print(test.shape)
test.head()

Padding data to longest sequence with length: 11535


/usr/local/Caskroom/miniconda/base/envs/cedalion/lib/python3.10/site-packages/xarray/core/variable.py:306: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


(196095, 428)


0         1         2         3         4         5         6     
0 -0.453743 -0.564715 -0.377385 -0.824645 -0.841382 -0.610995  0.435185  \
0 -0.528239 -0.617457 -0.428352 -0.877047 -1.042706 -0.718649 -0.005403   
0 -0.556833 -0.653591 -0.441188 -0.924813 -1.139435 -0.800622 -0.020688   
0 -0.457469 -0.622616 -0.402936 -0.872273 -0.955246 -0.670531  0.707054   
0 -0.427606 -0.542865 -0.339193 -0.797756 -0.873110 -0.564392  0.985954   

        7         8         9    ...       418       419       420       421   
0  0.553305 -0.612950 -0.658194  ...  1.110651  0.032406  0.360596  0.408561  \
0  0.516707 -0.666865 -0.581255  ...  1.444965  0.052339  0.369538  0.360814   
0  0.508694 -0.742322 -0.557370  ...  0.664919 -0.016350  0.350973 -0.354544   
0  0.498206 -0.592676 -0.463784  ...  0.431476  0.050230  0.378439  1.584142   
0  0.508709 -0.487986 -0.672742  ...  0.580905  0.068477  0.385932  1.106890   

        422       423       424       425       426       427  
0  0.706638  0.673319  0.427281  0.941846  0.862790  0.045816  
0  0.697427  0.694215  0.293682  0.927723  0.830082 -0.007813  
0  0.666938  0.663754  0.331351  0.949278  0.801049 -0.255246  
0  0.697774  0.662882  0.223749  0.992944  0.809655  0.005065  
0  0.683338  0.672764  0.307312  0.999986  0.838859  0.122165  

[5 rows x 428 columns]

In [15]:
TRAIN = test[:round((len(test) * 4/5))]
TRAIN.shape

(156876, 428)

In [16]:
TEST = test[round((len(test) * 4/5)):]
TEST.shape

(39219, 428)

In [13]:
TRAIN.to_csv("../fnirs_data/csv_format/vfc_high_density_TRAIN.csv")
TEST.to_csv("../fnirs_data/csv_format/vfc_high_density_TEST.csv")


mini_train = TRAIN[TRAIN.index < 3]
mini_test = TEST[TEST.index < 2]

mini_train.to_csv("/Users/idalabbackup/code/mvts_transformer_/imputation/vfc_high_density_TRAIN_mini.csv")
mini_test.to_csv("/Users/idalabbackup/code/mvts_transformer_/imputation/vfc_high_density_TEST_mini.csv")



# OPEN QUESTIONS
-----
- How to determine location based on xarray?
- If we remove noisy channels and fill with 0, can we also pad with 0?
- Should we just pad to a constant for our experiments?
- Mention raw file in load snirf
- Do we need to include this into cedalion fast? (dependency issues very likely)
- Talk to Eike about attributes?
- How to cut data for testing?
- Look into transduction?
- Add a learnable convolutional layer
- Does feature exclusion also work for testing data? 

In [14]:
print(f"{list(range(428//2, 428))}")

[214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,